---
# tasks file for nodejs
- name: install dependencies
  apt:
    name: apt-transport-https
    state: present
- name: add nodejs key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
    id: 68576280
- name: add nodejs repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{version}}.x {{ansible_distribution_release}} main'
    state: present
    filename: 'node'
    update_cache: yes
- name: install packages
  apt:
    name: nodejs
    state: present
- name: update npm packages
  npm:
    state: latest
    global: yes
