---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: ubuntu18.04
  #   image: finaldes/docker-ubuntu-ansible:bionic-20200403
  #   pre_build_image: true
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  - name: ubuntu16.04
    image: finaldes/docker-ubuntu-ansible:xenial-20200326
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
