---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu16.04
    image: finaldes/docker-ubuntu-ansible:xenial-20200326_2
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
